services:
  unifi-os-server:
    image: ghcr.io/mxkissnr/unifi-os-server:latest
    container_name: unifi-os-server
    privileged: true
    cgroup: host
    extra_hosts:
      host.docker.internal: host-gateway
    tmpfs:
      - /run:exec
      - /run/lock
      - /tmp:exec
      - /var/lib/journal
      - /var/opt/unifi/tmp:size=64m
    environment:
      - UOS_SYSTEM_IP=127.0.0.1
      - MONGO_INTERNAL=true
    volumes:
      - ./uosserver:/var/lib/uosserver
      - ./var-lib-unifi:/var/lib/unifi
      - ./data:/data
    ports:
      - 11443:443
      - 8080:8080
      - 3478:3478/udp
      - 10003:10003/udp
      - 5005:5005
      - 9543:9543
      - 6789:6789
      - 8444:8444
      - 5514:5514/udp
      - 127.0.0.1:11084:11084
      - 5671:5671
      - 8880:8880
      - 8881:8881
      - 8882:8882
    restart: unless-stopped
